export const ActionTypes = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT: "LOGOUT",
  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  ADD_BUSINESS_REQUEST: "ADD_BUSINESS_REQUEST",
  ADD_BUSINESS_SUCCESS: "ADD_BUSINESS_SUCCESS",
  GET_BUSINESSES_REQUEST: "GET_BUSINESSES_REQUEST",
  GET_BUSINESSES_SUCCESS: "GET_BUSINESSES_SUCCESS",
  ADD_SERVICE_REQUEST: "ADD_SERVICE_REQUEST",
  ADD_SERVICE_SUCCESS: "ADD_SERVICE_SUCCESS",
  GET_SERVICE_REQUEST: "GET_SERVICE_REQUEST",
  GET_SERVICE_SUCCESS: "GET_SERVICE_SUCCESS"
};
